---
title: "esm_204_hw3"
author: "Oswaldo Felix, Derek Nguyen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup
```{r}
library(tidyverse)
library(tidyr)
library(ggplot2)
library(janitor)
library(gridExtra)
```

```{r}
gas_data <- read_csv("gas_data.csv") %>% 
  clean_names()
```

# Exploration
```{r}
plot_low <- ggplot(data = gas_data, aes(x = price_dollars, y = q_low_gallons)) +
  geom_point()+
  theme_minimal()
plot_low

plot_high <- ggplot(data = gas_data, aes(x = price_dollars, y = q_high_gallons)) +
  geom_point() +
  theme_minimal()
plot_high

grid.arrange(plot_low, plot_high, ncol = 2, top = "Demand for High and Low Consumers")
```

# Questions 1 & 2
```{r}
# Regression models for high and low income consumers (demand curves)

# Low (demand curve (quantity-based))
lm_low_q <- lm(price_dollars ~ q_low_gallons, data = gas_data)
lm_low_q

# High (demand curve (quantity-based))
lm_high_q <- lm(price_dollars ~ q_high_gallons, data = gas_data)
lm_high_q

# Low (demand curve (price-based))
lm_low_p <- lm(q_low_gallons ~ price_dollars, data = gas_data)
lm_low_p

# High (demand curve (price-based))
lm_high_p <- lm(q_high_gallons ~ price_dollars, data = gas_data)
lm_high_p
```

```{r}
# Functions 
# demand (quantity-based) 1.
predict_demand <- function(q, model){
  b0 <- model$coefficients[1]
  b1 <- model$coefficients[2]
  predicted_demand <- b0 + b1*q
  return(predicted_demand)
}

# low demand (price-based) 1.
low_demand <- function(p){
  c0 <- lm_low_p$coefficients[1]
  c1 <- lm_low_p$coefficients[2]
  demand <- c0 + c1*p
  return(demand)
}

# high demand (price-based) 1.
high_demand <- function(p){
  c0 <- lm_high_p$coefficients[1]
  c1 <- lm_high_p$coefficients[2]
  demand <- c0 + c1*p
  return(demand)
}

# agg demand (price-based) 1.
aggregate_demand <- function(p){
  c0 <- lm_low_p$coefficients[1]
  c1 <- lm_low_p$coefficients[2]
  d0 <- lm_high_p$coefficients[1]
  d1 <- lm_high_p$coefficients[2]
  # aggregated_demand <- ((p-c0)/c1) + ((p-d0)/d1)
  aggregated_demand <- c0+d0 + (c1+d1)*p
  return(aggregated_demand)
}

# Quantity at price of $3
q_bar <- aggregate_demand(3)

slope = 3/q_bar
slope_inv = q_bar/3

# supply (quantity-based) 1.
predict_supply <- function(q){
    predicted_supply <- slope*q
  return(predicted_supply)
}

# supply (price-based) 5.
predict_supply_p <- function(p){
    predicted_supply <- slope_inv*p
  return(predicted_supply)
}

```

```{r}
# Welfare calculations
# Calculate red triangle 2.
low_upper <- lm_low_q$coefficients[1]
low_cs <- integrate(low_demand, lower = 3, upper = low_upper)
welfare_l <- low_cs$value

# Calculate blue triangle 2.
high_upper <- lm_high_q$coefficients[1]
high_cs <- integrate(high_demand, lower = 3, upper = high_upper)
welfare_h <- high_cs$value

# Total welfare
total_cs <- welfare_l + welfare_h
```

```{r}
# Producer welfare
# Calculate orange triangle 1.
ps <- integrate(predict_supply, lower = 0, upper = q_bar)
welfare_p <- ps$value

# Environmental cost 1.
cost_env <- 1.5*q_bar
```

```{r}
# Visualization set up
quantity_h <-  seq(from = 1, to = 600001, by = 31579)
graph_h <- predict_demand(quantity_h, lm_high_q)

quantity_l <-  seq(from = 1, to = 600001, by = 31579)
graph_l <- predict_demand(quantity_l, lm_low_q)

agg_price <- seq(from = 1+(10.8/19), to = 11.8, by = 10.8/19)
agg_demand <- aggregate_demand(agg_price)

supply_q <- seq(from = 1, to = 700017, by = 36843)
supply <- predict_supply(supply_q)

# Dataframe set up
predict_df <- data.frame(gas_data$price_dollars, gas_data$q_high_gallons, gas_data$q_low_gallons, quantity_h, graph_h, quantity_l, graph_l, agg_demand, supply, supply_q, agg_price) %>% 
  mutate(low_q = gas_data.q_low_gallons,
         high_q = gas_data.q_high_gallons,
         price_q = gas_data.price_dollars)

# Plot
ggplot(data = predict_df, aes(x = quantity_h, y = graph_h))+
  geom_line(aes(x = graph_l, y = quantity_l), color = "red") +
  geom_line(aes(x = graph_h, y = quantity_h), color = "blue") +
  geom_point(aes(x = price_q, y = low_q), color = "firebrick") +
  geom_point(aes(x = price_q, y = high_q), color = "blue4") +
  geom_line(aes(x = agg_price, y = agg_demand), color = "blueviolet") +
  geom_line(aes(x = supply, y = supply_q), color = "orange") +
  geom_vline(aes(xintercept = 3), linetype = "dashed", alpha = 0.5) +
  geom_hline(aes(yintercept = q_bar), linetype = "dashed", alpha = 0.5) +
  scale_x_continuous(limits = c(0,17), expand = c(0,0)) +
  theme_minimal() +
  labs(x = "Price [$/gal]", y = "Quantity", title = "Econ Curves") +
  coord_flip()

```

# Question 3
```{r}
predict_supply_tax <- function(p){
    predicted_supply <- slope_inv*(p - 1)
  return(predicted_supply)
}
price_new <- uniroot(function(x) aggregate_demand(x) - predict_supply_tax(x), c(0.01, 10)) 

p_new <- price_new$root # b.

q_new <- aggregate_demand(p_new) # a.

# Welfare of high income
high_upper <- lm_high_q$coefficients[1]
high_cs_new <- integrate(high_demand, lower = p_new, upper = high_upper)
welfare_h_new <- high_cs_new$value # c.

# Welfare of low income
low_upper <- lm_low_q$coefficients[1]
low_cs_new <- integrate(low_demand, lower = p_new, upper = low_upper)
welfare_l_new <- low_cs_new$value # d.

# Welfare of gas producers
ps_new <- integrate(predict_supply_tax, lower = 0, upper = p_new)
welfare_p_new <- (p_new-1) * q_new - ps_new$value # e.

# Local environmental damage
cost_env_new_l <- 1.5*q_new # f.

# Global environmental damage
cost_env_new_g <- 0.5*q_new # g.

# Total revenue from tax # h.
tax_rev <- 1*q_new

# Set up for graph
supply_q_new <- seq(from = 1, to = 800014, by = 42106)
supply_new <- predict_supply(supply_q_new)

# Visualization
ggplot(data = predict_df, aes(x = quantity_h, y = graph_h))+
  geom_line(aes(x = graph_l, y = quantity_l), color = "red") +
  geom_line(aes(x = graph_h, y = quantity_h), color = "blue") +
  geom_point(aes(x = price_q, y = low_q), color = "firebrick") +
  geom_point(aes(x = price_q, y = high_q), color = "blue4") +
  geom_line(aes(x = agg_price, y = agg_demand), color = "blueviolet") +
  geom_line(aes(x = supply_new, y = supply_q), color = "orange") +
  geom_vline(aes(xintercept = 4), linetype = "dashed", alpha = 0.5) +
  geom_hline(aes(yintercept = q_new), linetype = "dashed", alpha = 0.5) +
  scale_x_continuous(limits = c(0,15), expand = c(0,0)) +
  #scale_y_continuous(limits = c(500000, 600000)) +
  theme_minimal() +
  labs(x = "Price [$/gal]", y = "Quantity", title = "Econ Curves") +
  coord_flip()

```


# Question 4 
```{r}
# pre-tax proportion
q_low <- low_demand(3)
q_high <- high_demand(3)
prop_low <- q_low/q_bar
prop_high <- q_high/q_bar 

# No Tax
welfare_h_new3 <- welfare_h
welfare_l_new3 <- welfare_l - cost_env_new_l

# Tax of $1
welfare_l_new2 <- welfare_l_new + prop_low*tax_rev - cost_env_new_l # b.
welfare_h_new2 <- welfare_h_new + prop_high*tax_rev # a.
welfare_p_new2 <- (p_new-1) * q_new - ps_new$value

# Set up for $5
predict_supply_tax_5 <- function(p){
    predicted_supply <- slope_inv*(p - 5)
  return(predicted_supply)
}
price_new2 <- uniroot(function(x) aggregate_demand(x) - predict_supply_tax_5(x), c(0.01, 10)) 
p_new2 <- price_new2$root # b.

q_new2 <- aggregate_demand(p_new2) # a.

# Welfare of high income a.
high_cs_new2 <- integrate(high_demand, lower = p_new2, upper = high_upper)
welfare_h_new2_5 <- high_cs_new2$value + prop_high*p_new2*q_new2

# Welfare of low income b.
low_cs_new2 <- integrate(low_demand, lower = p_new2, upper = low_upper)
welfare_l_new2_5 <- low_cs_new2$value + prop_low*p_new2*q_new2 - cost_env_new_l

# Welfare of producers c.
ps_new2 <- integrate(predict_supply, lower = 0, upper = q_new2)
welfare_p_new2_5 <- (p_new2-5) * q_new2 - ps_new2$value

# New tax revnue
tax_rev_new2_5 <- 5*q_new2

# New environmental cost
cost_env_new2_5 <- 1.5*q_new2

# Tax of $5
welfare_l_new2_5 <- welfare_l_new2 + prop_low*tax_rev_new2 - cost_env_new2
welfare_h_new2_5 <- welfare_h_new2 + prop_high*tax_rev_new2
```


# Question 5
```{r}
# New demand function
# demand halved (either-based) 
predict_demand_half <- function(n, model){
  b0 <- model$coefficients[1]
  b1 <- model$coefficients[2]
  predicted_demand <- 0.5*b0 + b1*n
  return(predicted_demand)
}

aggregate_demand_half <- function(p){
  c0 <- lm_low_q$coefficients[1]
  c1 <- lm_low_q$coefficients[2]
  d0 <- lm_high_q$coefficients[1]
  d1 <- lm_high_q$coefficients[2]
  aggregated_demand <- ((p - 0.5*c0)/c1) + ((p - 0.5*d0)/d1)
  return(aggregated_demand)
}

solution <- uniroot(function(x) aggregate_demand_half(x) - predict_supply_p(x), c(0.01, 10))

# check
# aggregate_demand_half(solution$root)
# predict_supply_p(solution$root)


# High consumers a.
q_high_half <- predict_demand_half(solution$root, lm_high_p)

# Low consumers b.
q_low_half <- predict_demand_half(solution$root, lm_low_p)

# Gas Price c.
p_half <- solution$root

# Local environmental damage
cost_env_l_half <- 1.5 * (q_high_half + q_low_half)

# Global environmental damage
cost_env_g_half <- 0.5 * (q_high_half + q_low_half)
```

# Question 6
```{r}
# What tax will half q_bar?

q_bar_half <- q_low_half + q_high_half

predict_supply_tax_n <- function(t){
    predicted_supply <- slope*q_bar_half + t
  return(predicted_supply)
}

optimize(predict_supply_tax_n, c(0,10))

aggregate_demand(10.0)
```

